---

- hosts: all
  become: true
  tasks:
  
  - name: install apache and php packages for CentOs
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes

    when: ansible_distribution == "CentOs"

  - name: install apache 2 package for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

    when: ansible_distribution == "Ubuntu"
