---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    ansible.builtin.yum:
      update_cache: yes

  - name: install apache 2 package
    yum:
      name: httpd
      state: latest

  - name: enable httpd
    service:
      name: httpd
      enabled: yes
