---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOs)
    yum:
      update_only: yes
      update_cache: yes

    when: ansible_distribution == "CentOs"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes

    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for CentOs
    yum:
      name:
        - httpd
        - php
      state: latest

    when: ansible_distribution == "CentOs"

  - name: install apache 2 package for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest

    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    yum:
      name: mariadb
      state: latest
  
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest

    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
